### PR TITLE
BLIS now provides 64 bit binaries, add a LoopVectorization matmul

### LINKED ISSUE #54: CI is failing on master

### PR DESCRIPTION
**Pull request by chriselrod**
Closes #53 
Fixes #54

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
What's the earliest version of LV that has `@avxt`? We could just require that, no need to support old versions of LV for a benchmarking library.

**Comment by chriselrod** [comment]
Oops, 0.12 was the first version. I'll update the compat.

**Comment by chriselrod** [comment]
Tests passed locally, so this should fix #54

**Comment by DilumAluthge** [comment]
We should disable the Pkg server for the Documentation job.

**Comment by chriselrod** [comment]
How do we do that?

**Comment by DilumAluthge** [comment]
Let's see if that is sufficient.

**Comment by chriselrod** [comment]
Great, doc tests passed.

**Comment by DilumAluthge** [comment]
Worth tagging a new release?

**Comment by chriselrod** [comment]
Yes, go for it.

**Pull request merged**
